#!/bin/bash

cp -r ~/.config/hypr/hyprland.conf .config/hypr
cp -r ~/.config/kitty/kitty.conf .config/kitty
cp -r ~/.config/mpd/mpd.conf .config/mpd
cp -r ~/.config/ncmpcpp/config .config/ncmpcpp
cp -r ~/.config/ncmpcpp/bindings .config/ncmpcpp
cp -r ~/.config/zathura/zathurarc .config/zathura
cp -r ~/.emacs.d/config.org .emacs.d
cp -r ~/.emacs.d/init.el .emacs.d
